# Generated by Django 4.0.6 on 2022-07-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='created_at',
            new_name='upload_timestamp',
        ),
        migrations.AddField(
            model_name='video',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
