# Generated by Django 4.0.6 on 2022-07-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_alter_video_length_alter_video_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='upload_timestamp',
            new_name='upload_date',
        ),
    ]
